# ert tests

name: ert
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        sudo apt-get install units
        sudo apt-get install emacs && emacs --version
    - name: Run
      run: emacs -batch -l subr-x -l ./units-mode.el -l ert -l ./tests/units-mode-tests.el -f ert-run-tests-batch-and-exit
